"""Add errors table

Revision ID: 66feab46c31b
Revises: 6612c21e224a
Create Date: 2025-12-07 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66feab46c31b'
down_revision = '6612c21e224a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), server_default='error', nullable=True),
    sa.Column('resolved', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_errors_id'), 'errors', ['id'], unique=False)
    op.create_index(op.f('ix_errors_error_type'), 'errors', ['error_type'], unique=False)
    op.create_index(op.f('ix_errors_user_id'), 'errors', ['user_id'], unique=False)
    op.create_index(op.f('ix_errors_session_id'), 'errors', ['session_id'], unique=False)
    op.create_index(op.f('ix_errors_request_id'), 'errors', ['request_id'], unique=False)
    op.create_index(op.f('ix_errors_created_at'), 'errors', ['created_at'], unique=False)
    op.create_index(op.f('ix_errors_severity'), 'errors', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_errors_severity'), table_name='errors')
    op.drop_index(op.f('ix_errors_created_at'), table_name='errors')
    op.drop_index(op.f('ix_errors_request_id'), table_name='errors')
    op.drop_index(op.f('ix_errors_session_id'), table_name='errors')
    op.drop_index(op.f('ix_errors_user_id'), table_name='errors')
    op.drop_index(op.f('ix_errors_error_type'), table_name='errors')
    op.drop_index(op.f('ix_errors_id'), table_name='errors')
    op.drop_table('errors')
    # ### end Alembic commands ###
